#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNBCWeb.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GoldSilverMoneyDb")]
	public partial class GoldSilverMoneyDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPayPalSelectOption(PayPalSelectOption instance);
    partial void UpdatePayPalSelectOption(PayPalSelectOption instance);
    partial void DeletePayPalSelectOption(PayPalSelectOption instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public GoldSilverMoneyDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GoldSilverMoneyDbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GoldSilverMoneyDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoldSilverMoneyDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoldSilverMoneyDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GoldSilverMoneyDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PayPalSelectOption> PayPalSelectOptions
		{
			get
			{
				return this.GetTable<PayPalSelectOption>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_addOrderLogItem")]
		public int usp_addOrderLogItem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string sessionId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eventType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string eventDetail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionId, eventType, eventDetail);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PayPalSelectOptions")]
	public partial class PayPalSelectOption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _optionId;
		
		private int _ProductId;
		
		private int _OptionValue;
		
		private string _OptionText;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnoptionIdChanging(int value);
    partial void OnoptionIdChanged();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnOptionValueChanging(int value);
    partial void OnOptionValueChanged();
    partial void OnOptionTextChanging(string value);
    partial void OnOptionTextChanged();
    #endregion
		
		public PayPalSelectOption()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int optionId
		{
			get
			{
				return this._optionId;
			}
			set
			{
				if ((this._optionId != value))
				{
					this.OnoptionIdChanging(value);
					this.SendPropertyChanging();
					this._optionId = value;
					this.SendPropertyChanged("optionId");
					this.OnoptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL")]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionValue", DbType="Int NOT NULL")]
		public int OptionValue
		{
			get
			{
				return this._OptionValue;
			}
			set
			{
				if ((this._OptionValue != value))
				{
					this.OnOptionValueChanging(value);
					this.SendPropertyChanging();
					this._OptionValue = value;
					this.SendPropertyChanged("OptionValue");
					this.OnOptionValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this.OnOptionTextChanging(value);
					this.SendPropertyChanging();
					this._OptionText = value;
					this.SendPropertyChanged("OptionText");
					this.OnOptionTextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productId;
		
		private string _Title;
		
		private string _Description;
		
		private decimal _PriceInGbp;
		
		private string _PayPalButtonId;
		
		private System.Nullable<System.DateTime> _CreatedOrLastUpdated;
		
		private System.Nullable<int> _OrderPosition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIdChanging(int value);
    partial void OnproductIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPriceInGbpChanging(decimal value);
    partial void OnPriceInGbpChanged();
    partial void OnPayPalButtonIdChanging(string value);
    partial void OnPayPalButtonIdChanged();
    partial void OnCreatedOrLastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOrLastUpdatedChanged();
    partial void OnOrderPositionChanging(System.Nullable<int> value);
    partial void OnOrderPositionChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				if ((this._productId != value))
				{
					this.OnproductIdChanging(value);
					this.SendPropertyChanging();
					this._productId = value;
					this.SendPropertyChanged("productId");
					this.OnproductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceInGbp", DbType="Money NOT NULL")]
		public decimal PriceInGbp
		{
			get
			{
				return this._PriceInGbp;
			}
			set
			{
				if ((this._PriceInGbp != value))
				{
					this.OnPriceInGbpChanging(value);
					this.SendPropertyChanging();
					this._PriceInGbp = value;
					this.SendPropertyChanged("PriceInGbp");
					this.OnPriceInGbpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayPalButtonId", DbType="NVarChar(255)")]
		public string PayPalButtonId
		{
			get
			{
				return this._PayPalButtonId;
			}
			set
			{
				if ((this._PayPalButtonId != value))
				{
					this.OnPayPalButtonIdChanging(value);
					this.SendPropertyChanging();
					this._PayPalButtonId = value;
					this.SendPropertyChanged("PayPalButtonId");
					this.OnPayPalButtonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOrLastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOrLastUpdated
		{
			get
			{
				return this._CreatedOrLastUpdated;
			}
			set
			{
				if ((this._CreatedOrLastUpdated != value))
				{
					this.OnCreatedOrLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._CreatedOrLastUpdated = value;
					this.SendPropertyChanged("CreatedOrLastUpdated");
					this.OnCreatedOrLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPosition", DbType="Int")]
		public System.Nullable<int> OrderPosition
		{
			get
			{
				return this._OrderPosition;
			}
			set
			{
				if ((this._OrderPosition != value))
				{
					this.OnOrderPositionChanging(value);
					this.SendPropertyChanging();
					this._OrderPosition = value;
					this.SendPropertyChanged("OrderPosition");
					this.OnOrderPositionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
